{% set name = "torchdiffeq" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe75f434b9090ac0c27702e02bed21472b0f87035be6581f51edc5d4013ea31a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch
    - scipy

test:
  imports:
    - torchdiffeq
    - torchdiffeq._impl

about:
  home: https://github.com/rtqichen/torchdiffeq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ODE solvers and adjoint sensitivity analysis in PyTorch.
  doc_url: https://pypi.org/project/torchdiffeq/#description
  dev_url: https://github.com/rtqichen/torchdiffeq

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
