{% set name = "torchdiffeq" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31e3da7642432cf949950094e670f923c858033a3b5553da3c88083716f1cfb1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pytorch-cpu

test:
  imports:
    - torchdiffeq
    - torchdiffeq._impl

about:
  home: https://github.com/rtqichen/torchdiffeq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ODE solvers and adjoint sensitivity analysis in PyTorch.
  doc_url: https://pypi.org/project/torchdiffeq/#description
  dev_url: https://github.com/rtqichen/torchdiffeq

extra:
  recipe-maintainers:
    - ndmaxar
    - rluria14
    - oblute
